# Problem 1 

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'c:\Users\Casper\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([32,45,67,89,12])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(array))


[12 32 45 67 89]


# Problem 2

In [6]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
sayilar = np.array([10,15,30,45,60])
print(sayilar)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
sayilar2 = np.arange(5,15)
print(sayilar2)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
sayilar3 = np.arange(50,100,5)
print(sayilar3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayilar4 = np.zeros(10)
print(sayilar4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayilar5 = np.ones(10)
print(sayilar5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
sayilar6 = np.linspace(0,100,5)
print(sayilar6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
random_numbers = np.random.randint(10, 31, size = 5)
print(random_numbers)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
random_numbers2 = np.random.uniform(-1, 1, size = 10)
print(random_numbers2)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random_numbers3 = np.random.randint(10, 50, size = (3, 5))
print(random_numbers3)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(random_numbers3.sum(axis = 0))
print(random_numbers3.sum(axis = 1))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(random_numbers3.max())
print(random_numbers3.min())
print(random_numbers3.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(random_numbers3.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
random_numbers4 = np.random.randint(10, 20, size = 8)
print(random_numbers4[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(random_numbers4[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(random_numbers3[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(random_numbers3[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(random_numbers3[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(random_numbers3**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
random_numbers5 = np.random.randint(-50, 50, size = (3,5))
print((random_numbers5 > 0 ) & (random_numbers5 % 2 == 0))

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[11 17 18 25 12]
[-0.39711616 -0.8538816  -0.49948091 -0.65375853 -0.93858034 -0.36645364
 -0.25951848 -0.65278215 -0.17525813  0.13373563]
[[48 38 13 48 23]
 [16 47 14 43 38]
 [48 33 11 40 43]]
[112 118  38 131 104]
[170 158 175]
48
11
33.53333333333333
0
[19 15 11]
[15 13 14 19 11 11 15 19]
[48 38 13 48 23]
14
[48 16 48]
[[2304 1444  169 2304  529]
 [ 256 2209  196 1849 1444]
 [2304 1089  121 1600 1849]]
[[False False False False False]
 [ True False False False False]
 [False False False False False]]
