# Problem 1

In [6]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
import random
matris = [[random.randint(0, 10) for j in range(5)] for i in range(5)]
print(matris)

# 3 - matris'in boyutunu öğrenin
matris = [[2, 9, 6, 3, 10], [4, 3, 4, 1, 5], [6, 7, 0, 3, 6], [3, 10, 0, 8, 1], [4, 8, 4, 5, 0]]
satir_sayisi = len(matris)
sutun_sayisi = len(matris[0])
print("Matris boyutu:", satir_sayisi, "x", sutun_sayisi)

# 4 - matris'i yeniden boyutlandırın
matris = [[2, 9, 6, 3, 10], [4, 3, 4, 1, 5], [6, 7, 0, 3, 6], [3, 10, 0, 8, 1], [4, 8, 4, 5, 0]]
dizi = np.array(matris).flatten()
yeniden_boyutlandirilmis_matris = np.resize(matris, (3, 10))
print(yeniden_boyutlandirilmis_matris)

# 5 - matris'in boyut sayısını öğrenin
satir_sayisi = len(yeniden_boyutlandirilmis_matris)
sutun_sayisi = len(yeniden_boyutlandirilmis_matris[0])
print("Matris boyutu:", satir_sayisi, "x", sutun_sayisi)

[[8, 8, 4, 5, 7], [10, 3, 9, 6, 6], [2, 8, 2, 5, 0], [10, 6, 7, 10, 7], [0, 1, 4, 2, 5]]
Matris boyutu: 5 x 5
[[ 2  9  6  3 10  4  3  4  1  5]
 [ 6  7  0  3  6  3 10  0  8  1]
 [ 4  8  4  5  0  2  9  6  3 10]]
Matris boyutu: 3 x 10


# Problem 2

In [9]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris = np.arange(1, 11, 2)
matris = np.tile(matris, (5, 1))
print(matris)

# 2 - Oluşturduğunuz matrisi parçalayın
matris = np.arange(1, 11, 2)
matris = np.tile(matris, (5, 1))
alt_matrisler = np.split(matris, 5)
for alt_matris in alt_matrisler:
    print(alt_matris)

# 3 - Parçalanmış matrisleri birleştirin
matris = np.arange(1, 11, 2)
matris = np.tile(matris, (5, 1))
alt_matrisler = np.split(matris, 5)
birlesmis_matris = np.concatenate(alt_matrisler)
print(birlesmis_matris)


[[1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]]
[[1 3 5 7 9]]
[[1 3 5 7 9]]
[[1 3 5 7 9]]
[[1 3 5 7 9]]
[[1 3 5 7 9]]
[[1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]]


# Problem 3

In [12]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matris = np.arange(5, 101, 2)
np.random.shuffle(matris)
matris = matris[:10]
matris = matris.reshape(2, 5)
print(matris)

# 2 - matris'in özelliklerini inceleyin
matris = np.array([[34, 40, 24, 38, 22],[20, 24, 22, 30, 36],[38, 40, 22, 30, 36],[28, 30, 36, 34, 22],[36, 34, 24, 20, 26]])
boyut = matris.shape
eleman_sayisi = matris.size
maksimum = np.max(matris)
minimum = np.min(matris)
ortalamasi = np.mean(matris)
standart_sapma = np.std(matris)
print("Matris boyutu:", boyut)
print("Matris eleman sayısı:", eleman_sayisi)
print("Matris maksimum değeri:", maksimum)
print("Matris minimum değeri:", minimum)
print("Matris ortalaması:", ortalamasi)
print("Matris standart sapması:", standart_sapma)


[[15 93 11 77 89]
 [91  5 99 75 83]]
Matris boyutu: (5, 5)
Matris eleman sayısı: 25
Matris maksimum değeri: 40
Matris minimum değeri: 20
Matris ortalaması: 29.84
Matris standart sapması: 6.643372637448542
